theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add :
  - separator
  - insertdate
  - inserttime
  - preview
  - zoom
  - separator
  - forecolor
  - backcolor
theme_advanced_buttons2_add :

theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - hr
  - removeformat
  - visualaid
  - separator
  - sub
  - sup
  - separator
  - charmap
  - fontselect
  - hr
  - textcolor
  - bullist
  - numlist
  - separator
  - outdent
  - indent
  - separator
  - undo
  - redo
  - separator
plugins:
  - table
  - fullscreen
  - advlist
  - autolink
  - lists
  - link
  - image
  - charmap
  - print
  - preview
  - anchor
  - searchreplace
  - visualblocks
  - code
  - fullscreen
  - insertdatetime
  - media
  - contextmenu
  - paste
  - pagebreak
  - template
  - hr